# Generated by Django 4.2.10 on 2024-02-08 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=50)),
                ('reservation_date', models.DateField()),
                ('reservation_time', models.CharField(choices=[('12pm', '12:00pm - 1.25pm'), ('2pm', '2:00pm - 3:45pm'), ('4pm', '4:00pm - 5:45pm'), ('6pm', '6:00pm - 7:45pm'), ('8pm', '8:00pm - 9:45pm')], max_length=10)),
                ('company_size', models.IntegerField(default=1)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
