# Generated by Django 4.2.10 on 2024-02-09 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='company_size',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
