# Generated by Django 4.2.10 on 2024-02-09 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_reservation_company_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['reservation_date', 'reservation_time']},
        ),
    ]
