# Generated by Django 4.2.10 on 2024-02-18 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_reservation_reservation_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['table_id', 'capacity']},
        ),
        migrations.RemoveField(
            model_name='table',
            name='quantity',
        ),
    ]
