# Generated by Django 4.2.10 on 2024-02-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_reservation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='additional_info',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
