# Generated by Django 4.2.10 on 2024-02-16 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_reservation_additional_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='id',
            new_name='reservation_id',
        ),
    ]
